// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: exam_track.
// - Entity ID: 102019b0630795c7487b9eaf9bcdf3ca266.
// - Entity Version: 102019b1079416a7e66b70c0ffc100c7a0c.
// - Task ID: 693b83460b35e4b62b0f24d1.
// - Task Root ID: 6938e05c60b30fd313d1ecfa.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ExamTrackExamType
 */
export enum ExamTrackExamType {
  Unspecified = 0,
  SAT = 1,
  ACT = 2,
  AP = 3,
  School = 4,
}



/**
 * Interface for ExamTrackModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ExamTrackModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  exam_type: ExamTrackExamType;
  subject_list: string[];
  active_status: boolean;
}

/**
 * ORM class for ExamTrack entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ExamTrackORM {
  private static instance: ExamTrackORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b0630795c7487b9eaf9bcdf3ca266';
    this.entityName = 'exam_track';
    this.entityVersion = '102019b1079416a7e66b70c0ffc100c7a0c';
    this.taskId = '693b83460b35e4b62b0f24d1';
    this.taskRootId = '6938e05c60b30fd313d1ecfa';
  }

  /**
   * Get singleton instance of ExamTrackORM
   */
  public static getInstance(): ExamTrackORM {
    if (!ExamTrackORM.instance) {
      ExamTrackORM.instance = new ExamTrackORM();
    }
    
    return ExamTrackORM.instance;
  }

  /**
   * Get all ExamTrack records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllExamTrack(): Promise<ExamTrackModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ExamTrack record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertExamTrack(data: ExamTrackModel[]): Promise<ExamTrackModel[]> {
    const structured = data.map((item) => CreateData(ExamTrackModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ExamTrack records
   */
  async purgeAllExamTrack(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ExamTrack records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listExamTrack(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ExamTrackModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get exam_track by Id index
   * This function gets data by index.
   */
  async getExamTrackById(
    id: string,
  ): Promise<ExamTrackModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exam_track by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExamTrackById(
    id: string,
    data: ExamTrackModel
  ): Promise<ExamTrackModel[]> {
    const index = createIndexId(
      id
    );

    const values = ExamTrackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exam_track by Id index
   */
  async deleteExamTrackById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exam_track by UserId index
   * This function gets data by index.
   */
  async getExamTrackByUserId(
    user_id: string,
  ): Promise<ExamTrackModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exam_track by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExamTrackByUserId(
    user_id: string,
    data: ExamTrackModel
  ): Promise<ExamTrackModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = ExamTrackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exam_track by UserId index
   */
  async deleteExamTrackByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exam_track by DataCreator index
   * This function gets data by index.
   */
  async getExamTrackByDataCreator(
    data_creator: string,
  ): Promise<ExamTrackModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exam_track by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExamTrackByDataCreator(
    data_creator: string,
    data: ExamTrackModel
  ): Promise<ExamTrackModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ExamTrackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exam_track by DataCreator index
   */
  async deleteExamTrackByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exam_track by DataUpdater index
   * This function gets data by index.
   */
  async getExamTrackByDataUpdater(
    data_updater: string,
  ): Promise<ExamTrackModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exam_track by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExamTrackByDataUpdater(
    data_updater: string,
    data: ExamTrackModel
  ): Promise<ExamTrackModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ExamTrackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exam_track by DataUpdater index
   */
  async deleteExamTrackByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ExamTrackModel data array
   */
  private resultToData(values: Data[]): ExamTrackModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ExamTrackModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ExamTrackModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ExamTrackModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ExamTrackModel => item !== null);
  }
}

/**
 * Convert ExamTrackModel data to Value array
 */
function ExamTrackModelToValues(data: ExamTrackModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'exam_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'subject_list', type: DataType.array, defaultValue: [] },
    { key: 'active_status', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ExamTrackModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ExamTrackModel data
 */
function ExamTrackModelFromValues(values: Value[]): ExamTrackModel {
  const data: Partial<ExamTrackModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'exam_type':
        data.exam_type = ParseValue(value, DataType.enumeration) as ExamTrackExamType;
        break;
      case 'subject_list':
        data.subject_list = ParseValue(value, DataType.array) as string[];
        break;
      case 'active_status':
        data.active_status = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as ExamTrackModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ExamTrackORM;