// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: quiz_question.
// - Entity ID: 102019b0630795b79b083b58d3652720065.
// - Entity Version: 102019b1079416a7e66b70c0ffc100c7a0c.
// - Task ID: 693b83460b35e4b62b0f24d1.
// - Task Root ID: 6938e05c60b30fd313d1ecfa.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for QuizQuestionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface QuizQuestionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  quiz_id: string;
  question_text: string;
  correct_answer: string;
  user_answer: string;
  is_correct: boolean;
}

/**
 * ORM class for QuizQuestion entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class QuizQuestionORM {
  private static instance: QuizQuestionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b0630795b79b083b58d3652720065';
    this.entityName = 'quiz_question';
    this.entityVersion = '102019b1079416a7e66b70c0ffc100c7a0c';
    this.taskId = '693b83460b35e4b62b0f24d1';
    this.taskRootId = '6938e05c60b30fd313d1ecfa';
  }

  /**
   * Get singleton instance of QuizQuestionORM
   */
  public static getInstance(): QuizQuestionORM {
    if (!QuizQuestionORM.instance) {
      QuizQuestionORM.instance = new QuizQuestionORM();
    }
    
    return QuizQuestionORM.instance;
  }

  /**
   * Get all QuizQuestion records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllQuizQuestion(): Promise<QuizQuestionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new QuizQuestion record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertQuizQuestion(data: QuizQuestionModel[]): Promise<QuizQuestionModel[]> {
    const structured = data.map((item) => CreateData(QuizQuestionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all QuizQuestion records
   */
  async purgeAllQuizQuestion(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List QuizQuestion records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listQuizQuestion(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[QuizQuestionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get quiz_question by Id index
   * This function gets data by index.
   */
  async getQuizQuestionById(
    id: string,
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_question by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizQuestionById(
    id: string,
    data: QuizQuestionModel
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexId(
      id
    );

    const values = QuizQuestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_question by Id index
   */
  async deleteQuizQuestionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_question by QuizId index
   * This function gets data by index.
   */
  async getQuizQuestionByQuizId(
    quiz_id: string,
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexQuizId(
      quiz_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_question by QuizId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizQuestionByQuizId(
    quiz_id: string,
    data: QuizQuestionModel
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexQuizId(
      quiz_id
    );

    const values = QuizQuestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_question by QuizId index
   */
  async deleteQuizQuestionByQuizId(
    quiz_id: string
  ): Promise<void> {
    const index = createIndexQuizId(
      quiz_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_question by DataCreator index
   * This function gets data by index.
   */
  async getQuizQuestionByDataCreator(
    data_creator: string,
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_question by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizQuestionByDataCreator(
    data_creator: string,
    data: QuizQuestionModel
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = QuizQuestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_question by DataCreator index
   */
  async deleteQuizQuestionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_question by DataUpdater index
   * This function gets data by index.
   */
  async getQuizQuestionByDataUpdater(
    data_updater: string,
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_question by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizQuestionByDataUpdater(
    data_updater: string,
    data: QuizQuestionModel
  ): Promise<QuizQuestionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = QuizQuestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_question by DataUpdater index
   */
  async deleteQuizQuestionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to QuizQuestionModel data array
   */
  private resultToData(values: Data[]): QuizQuestionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return QuizQuestionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as QuizQuestionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized QuizQuestionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is QuizQuestionModel => item !== null);
  }
}

/**
 * Convert QuizQuestionModel data to Value array
 */
function QuizQuestionModelToValues(data: QuizQuestionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'quiz_id', type: DataType.string, defaultValue: '' },
    { key: 'question_text', type: DataType.string, defaultValue: '' },
    { key: 'correct_answer', type: DataType.string, defaultValue: '' },
    { key: 'user_answer', type: DataType.string, defaultValue: '' },
    { key: 'is_correct', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof QuizQuestionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to QuizQuestionModel data
 */
function QuizQuestionModelFromValues(values: Value[]): QuizQuestionModel {
  const data: Partial<QuizQuestionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'quiz_id':
        data.quiz_id = ParseValue(value, DataType.string) as string;
        break;
      case 'question_text':
        data.question_text = ParseValue(value, DataType.string) as string;
        break;
      case 'correct_answer':
        data.correct_answer = ParseValue(value, DataType.string) as string;
        break;
      case 'user_answer':
        data.user_answer = ParseValue(value, DataType.string) as string;
        break;
      case 'is_correct':
        data.is_correct = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as QuizQuestionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for QuizId fields
 */
function createIndexQuizId(
  quiz_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, quiz_id, 'quiz_id'),
  ];

  return {
    fields: ['quiz_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default QuizQuestionORM;